	db 0 ; no more evolutions
	db 1, LEER
	db 1, EMBER
	db 4, EXTREMESPEED
	db 7, DRAGON_CLAW
	db 10, FLAME_WHEEL
	db 13, EXTREMESPEED
	db 16, LEER
	db 19, DRAGON_CLAW
	db 22, FLAME_WHEEL
	db 25, EXTREMESPEED
	db 28, LEER
	db 31, DRAGON_CLAW
	db 34, FLAMETHROWER
	db 37, EXTREMESPEED
	db 40, LEER
	db 43, DRAGON_CLAW
	db 46, FLAMETHROWER
	db 49, EXTREMESPEED
	db 52, OUTRAGE
	db 0 ; no more level-up moves
