	db 0 ; no more evolutions
	db 1, KARATE_CHOP
	db 1, LEER
	db 4, FURY_ATTACK
	db 7, PIN_MISSILE
	db 10, HORN_ATTACK
	db 10, FALSE_SWIPE
	db 13, LEER
	db 16, SHARPEN
	db 19, KARATE_CHOP
	db 20, FALSE_SWIPE
	db 22, PIN_MISSILE
	db 25, DOUBLE_EDGE
	db 28, STRUGGLE_BUG
	db 30, FALSE_SWIPE
	db 31, SHARPEN
	db 34, CROSS_CHOP
	db 37, MEGAHORN
	db 40, FALSE_SWIPE
	db 43, DOUBLE_EDGE
	db 46, SHARPEN
	db 49, CROSS_CHOP
	db 52, MEGAHORN
	db 0 ; no more level-up moves
