	db EVOLVE_HAPPINESS, TR_ANYTIME, BLISSEY
	db 0 ; no more evolutions
	db 1, POUND
	db 1, GROWL
	db 4, TAIL_WHIP
	db 7, SOFTBOILED
	db 10, SONICBOOM
	db 13, MINIMIZE
	db 16, SING
	db 19, EGG_BOMB
	db 22, LIGHT_SCREEN
	db 25, SEISMIC_TOSS
	db 28, CHARM
	db 31, SONICBOOM
	db 34, SOFTBOILED
	db 37, LIGHT_SCREEN
	db 40, DOUBLESLAP
	db 43, SING
	db 46, CHARM
	db 49, SEISMIC_TOSS
	db 52, SOFTBOILED
	db 0 ; no more level-up moves
