	db EVOLVE_LEVEL, 36, GENGAR
	db 0 ; no more evolutions
	db 1, LICK
	db 1, CONFUSE_RAY
	db 4, HYPNOSIS
	db 7, ACID
	db 10, SLUDGE
	db 13, CONFUSE_RAY
	db 16, SHADOW_BALL
	db 19, HYPNOSIS
	db 22, SLUDGE_BOMB
	db 25, NIGHT_SHADE
	db 28, CURSE
	db 31, MEAN_LOOK
	db 34, GIGA_DRAIN
	db 37, NIGHT_SHADE
	db 40, SHADOW_BALL
	db 43, HYPNOSIS
	db 46, DREAM_EATER
	db 49, SLUDGE_BOMB
	db 52, DESTINY_BOND
	db 0 ; no more level-up moves
