	db EVOLVE_LEVEL, 16, CHARMELEON
	db EVOLVE_ITEM, FIRE_STONE, TORCHIC
	db EVOLVE_ITEM, SUN_STONE, CHIMCHAR
	db 1, SCRATCH
	db 4, GROWL
	db 6, EMBER
	db 8, SMOKESCREEN
	db 12, DRAGONBREATH
	db 14, SCARY_FACE
	db 16, FLAME_WHEEL
	db 19, BITE
	db 22, WILL_O_WISP
	db 25, FIRE_FANG
	db 28, FLAMETHROWER
	db 32, FIRE_SPIN
	db 44, FIRE_BLAST
	db 48, ANCIENTPOWER
	db 52, DRAGON_CLAW
	db 0 ; no more level-up moves
