	db EVOLVE_LEVEL, 20, RATICATE
	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, TACKLE
	db 4, BITE
	db 7, SHARPEN
	db 10, QUICK_ATTACK
	db 13, TACKLE
	db 16, HYPER_FANG
	db 19, BITE
	db 20, FALSE_SWIPE
	db 22, SHARPEN
	db 25, QUICK_ATTACK
	db 28, SHARPEN
	db 30, FALSE_SWIPE
	db 31, CRUNCH
	db 34, SUPER_FANG
	db 37, HYPER_FANG
	db 40, QUICK_ATTACK
	db 40, FALSE_SWIPE
	db 43, SHARPEN
	db 46, CRUNCH
	db 49, SUPER_FANG
	db 52, HYPER_FANG
	db 0 ; no more level-up moves
