	db EVOLVE_ITEM, DUSK_STONE, DUSKNOIR
	db 0 ; no more evolutions
	db 1, ASTONISH
	db 1, LEER
	db 4, DISABLE
	db 7, CONFUSE_RAY
	db 10, NIGHT_SHADE
	db 13, WILL_O_WISP
	db 16, CURSE
	db 19, ASTONISH
	db 22, SCREECH
	db 25, DISABLE
	db 28, CONFUSE_RAY
	db 31, SHADOW_SNEAK
	db 34, FUTURE_SIGHT 
	db 37, CURSE
	db 40, DISABLE
	db 43, CONFUSE_RAY
	db 46, NIGHT_SHADE
	db 49, WILL_O_WISP
	db 52, SHADOW_BALL
	db 0 ; no more level-up moves
