	db 0 ; no more evolutions
	db 1, FAIRY_WIND
	db 1, PSYCHO_CUT
	db 4, GROWL
	db 7, DOUBLE_TEAM
	db 10, HYPNOSIS
	db 13, ZEN_HEADBUTT
	db 16, TELEPORT
	db 19, PSYCHO_CUT
	db 22, LOW_KICK
	db 25, FALSE_SWIPE
	db 28, DRAIN_PUNCH
	db 31, FUTURE_SIGHT
	db 34, CONFUSION
	db 35, PROTECT
	db 37, PSYCHO_CUT
	db 40, DRAIN_PUNCH
	db 41, CLOSE_COMBAT
	db 43, ZEN_HEADBUTT
	db 46, SHARPEN
	db 47, FALSE_SWIPE
	db 49, PSYCHO_CUT
	db 52, DRAIN_PUNCH
	db 0 ; no more level-up moves
