	db EVOLVE_LEVEL, 28, CAMERUPT
	db EVOLVE_STONE, DAWN_STONE, CHIMCHAR
	db EVOLVE_STONE, DUSK_STONE, MOLTRES
	db 0 ; no more evolutions
	db 1, GROWL
	db 1, TACKLE
	db 4, EMBER
	db 7, AMNESIA
	db 10, ROCK_THROW
	db 13, CURSE
	db 16, EMBER
	db 19, ANCIENTPOWER
	db 22, EARTH_POWER
	db 25, FLAME_WHEEL
	db 28, CURSE
	db 31, ROCK_SLIDE
	db 34, EARTH_POWER
	db 37, FLAMETHROWER
	db 40, POWER_GEM
	db 43, EARTHQUAKE
	db 46, ROCK_SLIDE
	db 49, EARTH_POWER
	db 52, FLAMETHROWER
	db 0 ; no more level-up moves
