	db EVOLVE_LEVEL, 18, LEDIAN
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, SUPERSONIC
	db 4, MACH_PUNCH
	db 7, PIN_MISSILE
	db 10, AERIAL_ACE
	db 13, LIGHT_SCREEN
	db 16, REFLECT
	db 19, PIN_MISSILE
	db 22, FEINT_ATTACK
	db 25, DRAIN_PUNCH
	db 28, AERIAL_ACE
	db 31, PIN_MISSILE
	db 34, FEINT_ATTACK
	db 37, DRAIN_PUNCH
	db 40, AERIAL_ACE
	db 43, PIN_MISSILE
	db 46, FEINT_ATTACK
	db 49, DRAIN_PUNCH
	db 52, AERIAL_ACE
	db 0 ; no more level-up moves
