	db EVOLVE_ITEM, FIRE_STONE, MAGMORTAR
	db 0 ; no more evolutions
	db 1, LEER
	db 1, EMBER
	db 4, SMOG
	db 7, SMOKESCREEN
	db 10, FLAME_WHEEL
	db 13, CONFUSE_RAY
	db 16, SCARY_FACE
	db 19, FIRE_PUNCH
	db 22, WILL_O_WISP
	db 25, SMOKESCREEN
	db 28, CONFUSE_RAY
	db 31, LOW_KICK
	db 34, FLAMETHROWER
	db 37, WILL_O_WISP
	db 40, FIRE_PUNCH
	db 43, SUNNY_DAY
	db 46, HYPER_BEAM
	db 49, AURA_SPHERE
	db 52, FIRE_BLAST
	db 0 ; no more level-up moves
