	db EVOLVE_LEVEL, 36, CHARIZARD
	db 1, SCRATCH
	db 4, GROWL
	db 6, EMBER
	db 8, SMOKESCREEN
	db 11, DRAGONBREATH
	db 14, SLASH
	db 16, FLAME_WHEEL
	db 19, BITE
	db 22, WILL_O_WISP
	db 25, FIRE_FANG
	db 28, FLAMETHROWER
	db 32, SLASH
	db 44, FIRE_BLAST
	db 48, ANCIENTPOWER
	db 52, DRAGON_CLAW
	db 0 ; no more level-up moves
