	db EVOLVE_LEVEL, 26, HYPNO
	db 0 ; no more evolutions
	db 1, HYPNOSIS
	db 1, POUND
	db 4, DISABLE
	db 7, PURSUIT
	db 10, HEADBUTT
	db 13, SCARY_FACE
	db 16, CONFUSION
	db 19, HYPNOSIS
	db 22, NIGHT_SHADE
	db 25, ZEN_HEADBUTT
	db 28, SCARY_FACE
	db 31, HYPNOSIS
	db 34, MEDITATE
	db 37, FEINT_ATTACK
	db 40, ZEN_HEADBUTT
	db 41, MEDITATE
	db 43, HYPNOSIS
	db 46, SPORE
	db 49, NIGHT_SLASH
	db 52, ZEN_HEADBUTT
	db 55, SPORE
	db 0 ; no more level-up moves
