	db 0 ; no more evolutions
	db 1, POISON_STING
	db 1, STRING_SHOT
	db 1, STRUGGLE_BUG
	db 1, HARDEN
	db 10, TWINEEDLE
	db 10, FURY_ATTACK
	db 10, HORN_ATTACK
	db 12, PURSUIT
	db 14, PIN_MISSILE
	db 16, POISON_JAB
	db 18, STEEL_WING
	db 20, SWORDS_DANCE
	db 22, TOXIC
	db 24, POISON_JAB
	db 26, HORN_ATTACK
	db 28, PIN_MISSILE
	db 30, STEEL_WING
	db 32, SWORDS_DANCE
	db 34, POISON_JAB
	db 36, TOXIC
	db 38, STEEL_WING
	db 40, SWORDS_DANCE
	db 42, POISON_JAB
	db 0 ; no more level-up moves
