	db EVOLVE_LEVEL, 30, LUCARIO
	db EVOLVE_HAPPINESS, TR_MORNDAY, LUCARIO
	db 0 ; no more evolutions
	db 1, QUICK_ATTACK
	db 1, ROCK_SMASH
	db 4, METAL_CLAW
	db 7, SHARPEN
	db 10, BULLET_PUNCH
	db 13, MACH_PUNCH
	db 16, JUMP_KICK
	db 19, SHARPEN
	db 22, BULLET_PUNCH
	db 25, MACH_PUNCH
	db 28, SCREECH
	db 31, JUMP_KICK
	db 34, METEOR_MASH
	db 37, CROSS_CHOP
	db 40, BULLET_PUNCH
	db 43, SWORDS_DANCE
	db 46, JUMP_KICK
	db 49, METEOR_MASH
	db 52, CROSS_CHOP
	db 0 ; no more level-up moves
