	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, FAIRY_WIND
	db 4, SAND_ATTACK
	db 7, QUICK_ATTACK
	db 10, SWIFT
	db 13, BITE
	db 16, CHARM
	db 19, DRAINING_KISS
	db 22, FAIRY_WIND
	db 25, REFLECT
	db 28, PSYCH_UP
	db 31, DOUBLE_KICK
	db 34, DAZZLING_GLEAM
	db 37, HYPER_VOICE
	db 40, REFLECT
	db 43, DRAINING_KISS
	db 46, DOUBLE_KICK
	db 49, HYPER_VOICE
	db 52, DAZZLING_GLEAM
	db 0 ; no more level-up moves
