	db EVOLVE_LEVEL, 20, NOCTOWL
	db 0 ; no more evolutions
	db 1, PECK
	db 1, ASTONISH
	db 4, REFLECT
	db 7, MEDITATE
	db 10, NIGHT_SHADE
	db 13, HYPNOSIS
	db 16, WING_ATTACK
	db 19, REFLECT
	db 22, SHADOW_CLAW
	db 25, NIGHT_SHADE
	db 28, ZEN_HEADBUTT
	db 31, HYPNOSIS
	db 34, WING_ATTACK
	db 37, SHADOW_CLAW
	db 40, NIGHT_SHADE
	db 43, ZEN_HEADBUTT
	db 46, HYPNOSIS
	db 49, WING_ATTACK
	db 52, SHADOW_CLAW
	db 0 ; no more level-up moves
