	db 0 ; no more evolutions
	db 1, GUST
	db 1, CONFUSION
	db 4, SWIFT
	db 7, THUNDERWAVE
	db 10, LIGHT_SCREEN
	db 13, CONFUSION
	db 16, SWIFT
	db 19, AIR_CUTTER
	db 22, PSYBEAM
	db 25, LIGHT_SCREEN
	db 28, THUNDERWAVE
	db 31, ANCIENTPOWER
	db 34, AIR_SLASH
	db 37, PSYCHIC
	db 40, LIGHT_SCREEN
	db 43, THUNDERWAVE
	db 46, ANCIENTPOWER
	db 49, AIR_SLASH
	db 52, PSYCHIC
	db 0 ; no more level-up moves
