	db 0 ; no more evolutions
	db 1, VICEGRIP
	db 1, HARDEN
	db 4, TWINEEDLE
	db 7, SEISMIC_TOSS
	db 10, BIND
	db 13, FALSE_SWIPE
	db 16, KARATE_CHOP
	db 19, TWINEEDLE
	db 22, QUICK_ATTACK
	db 25, DOUBLE_KICK
	db 28, FALSE_SWIPE
	db 31, TWINEEDLE
	db 34, BODY_SLAM
	db 37, PIN_MISSILE
	db 40, FALSE_SWIPE
	db 43, TWINEEDLE
	db 46, BODY_SLAM
	db 49, MEGAHORN
	db 52, DOUBLE_EDGE
	db 0 ; no more level-up moves

