	db 0 ; no more evolutions
	db 1, AURA_SPHERE
	db 1, BARRIER
	db 1, AMNESIA
	db 11, SHADOW_BALL
	db 16, PSYBEAM
	db 19, PSYCH_UP
	db 24, PSYCHIC
	db 29, TRANSFORM
	db 34, METRONOME
	db 39, ANCIENTPOWER
	db 43, RECOVER
	db 48, POWER_SWAP
	db 51, PSYSTRIKE
	db 56, FUTURE_SIGHT