	db EVOLVE_LEVEL, 30, RAMPARDOS
	db 0 ; no more evolutions
	db 1, LEER
	db 1, HEADBUTT
	db 4, ROCK_THROW
	Db 4, ROCK_SMASH
	db 7, ANCIENTPOWER
	db 10, STOMP
	db 13, KARATE_CHOP
	db 16, METAL_CLAW
	db 19, HEADBUTT
	db 22, ROCK_SLIDE
	db 22, JUMP_KICK
	db 25, SCREECH
	db 28, SCARY_FACE
	db 31, METEOR_MASH
	db 34, ZEN_HEADBUTT
	db 37, ROCK_SLIDE
	db 37, JUMP_KICK
	db 40, SCREECH
	db 43, SCARY_FACE
	db 43, JUMP_KICK
	db 43, ROCK_SLIDE
	db 46, METEOR_MASH
	db 49, ZEN_HEADBUTT
	db 52, ROCK_SLIDE
	db 52, JUMP_KICK
	db 0 ; no more level-up moves
