	db EVOLVE_LEVEL, 23, SEAKING
	db EVOLVE_ITEM, THUNDERSTONE, CHINCHOU
	db 0 ; no more evolutions
	db 1, PECK
	db 1, TAIL_WHIP
	db 4, SUPERSONIC
	db 7, HORN_ATTACK
	db 10, WATER_GUN
	db 13, WATER_PULSE
	db 16, PECK
	db 19, SHARPEN
	db 22, BODY_SLAM
	db 25, AGILITY
	db 28, WATERFALL
	db 31, SHARPEN
	db 34, POISON_JAB
	db 37, MEGAHORN
	db 40, WATERFALL
	db 43, SHARPEN
	db 46, POISON_JAB
	db 49, MEGAHORN
	db 52, WATERFALL
	db 0 ; no more level-up moves
