	db EVOLVE_LEVEL, 21, FORRETRESS
	db 0 ; no more evolutions
	db 1, HARDEN
	db 1, RAPID_SPIN
	db 4, TACKLE
	db 7, DEFENSE_CURL
	db 10, ROLLOUT
	db 13, DIG
	db 16, PIN_MISSILE
	db 19, IRON_DEFENSE
	db 22, CURSE
	db 25, BODY_SLAM
	db 28, DIG
	db 31, PIN_MISSILE
	db 34, CURSE
	db 37, SELFDESTRUCT
	db 40, DEFENSE_CURL
	db 43, ROLLOUT
	db 46, PIN_MISSILE
	db 49, IRON_HEAD
	db 52, EXPLOSION
	db 0 ; no more level-up moves
