	db EVOLVE_LEVEL, 28, KINGLER
	db 0 ; no more evolutions
	db 1, BUBBLE
	db 1, LEER
	db 4, VICEGRIP
	db 7, HARDEN
	db 10, CLAMP
	db 13, VICEGRIP
	db 16, METAL_CLAW
	db 19, CRABHAMMER
	db 22, SHARPEN
	db 25, STOMP
	db 28, FALSE_SWIPE
	db 31, SWORDS_DANCE
	db 34, METAL_CLAW
	db 37, BODY_SLAM
	db 40, CRABHAMMER
	db 41, FALSE_SWIPE
	db 43, RAZOR_SHELL
	db 46, SLAM
	db 49, SWORDS_DANCE
	db 52, GUILLOTINE
	db 55, PROTECT
	db 58, HYDRO_PUMP
	db 0 ; no more level-up moves
