	db 0 ; no more evolutions
	db 1, HARDEN
	db 1, CONFUSION
	db 4, ROCK_THROW
	db 7, TACKLE
	db 10, HYPNOSIS
	db 13, CONFUSION
	db 16, HARDEN
	db 19, ROCK_SLIDE
	db 22, PSYCHO_CUT
	db 25, MORNING_SUN
	db 28, LIGHT_SCREEN
	db 31, ROCK_SLIDE
	db 34, ZEN_HEADBUTT
	db 37, HYPNOSIS
	db 40, SWORDS_DANCE
	db 43, LIGHT_SCREEN
	db 46, ROCK_SLIDE
	db 49, ZEN_HEADBUTT
	db 52, EXPLOSION
	db 0 ; no more level-up moves
