	db EVOLVE_LEVEL, 25, URSARING
	db 0 ; no more evolutions
	db 1, SCRATCH
	db 1, LEER
	db 4, LICK
	db 7, FALSE_SWIPE
	db 10, FURY_SWIPES
	db 13, SWEET_SCENT
	db 16, FEINT_ATTACK
	db 19, LICK
	db 22, SLASH
	db 25, FALSE_SWIPE
	db 28, NIGHT_SLASH
	db 31, PLAY_ROUGH
	db 34, STRENGTH
	db 37, EARTHQUAKE
	db 40, FALSE_SWIPE
	db 43, NIGHT_SLASH
	db 46, PLAY_ROUGH
	db 49, STRENGTH
	db 52, EARTHQUAKE
	db 0 ; no more level-up moves
