	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, CURSE
	db 4, ROCK_THROW
	db 7, ANCIENTPOWER
	db 10, STOMP
	db 13, IRON_DEFENSE
	db 16, ROCK_SLIDE
	db 19, SAFEGUARD
	db 22, ROCK_SLIDE
	db 25, STOMP
	db 28, IRON_DEFENSE
	db 31, STOMP
	db 34, CURSE
	db 37, ROCK_THROW
	db 40, HYPER_BEAM
	db 43, IRON_DEFENSE
	db 46, ZAP_CANNON
	db 49, CURSE
	db 52, ROCK_SLIDE
	db 55, DRAIN_PUNCH
	db 58, ANCIENTPOWER
	db 61, ZAP_CANNON
	db 64, ROCK_SLIDE
	db 67, DRAIN_PUNCH
	db 80, EXPLOSION
	db 0 ; no more level-up moves
