	db EVOLVE_ITEM, DUSK_STONE, KINGDRA
	db 0 ; no more evolutions
	db 1, BUBBLE
	db 1, LEER
	db 4, SMOKESCREEN
	db 7, TWISTER
	db 10, WATER_GUN
	db 13, LEER
	db 16, SMOKESCREEN
	db 19, SWIFT
	db 22, ATTRACT
	db 25, BUBBLEBEAM
	db 28, DRAGON_PULSE
	db 31, SWIFT
	db 34, ATTRACT
	db 37, LASER_FOCUS
	db 40, HYPER_BEAM
	db 43, SWIFT
	db 46, DRAGON_DANCE
	db 49, HYDRO_PUMP
	db 51, RAIN_DANCE
	db 55, DRAGON_PULSE
	db 0 ; no more level-up moves