	db EVOLVE_LEVEL, 30, OMASTAR
	db 0 ; no more evolutions
	db 1, WATER_GUN
	db 1, ANCIENTPOWER
	db 4, WITHDRAW
	db 7, SAND_ATTACK
	db 10, BITE
	db 13, WATER_GUN
	db 16, SWIFT
	db 19, IRON_DEFENSE
	db 22, ANCIENTPOWER
	db 25, SWIFT
	db 28, IRON_DEFENSE
	db 31, ANCIENTPOWER
	db 34, BUBBLEBEAM
	db 37, POWER_GEM
	db 40, HYDRO_PUMP
	db 43, ANCIENTPOWER
	db 46, BUBBLEBEAM
	db 49, POWER_GEM
	db 52, HYDRO_PUMP
	db 0 ; no more level-up moves
