	db EVOLVE_ITEM, THUNDERSTONE, JOLTEON
	db EVOLVE_ITEM, WATER_STONE, VAPOREON
	db EVOLVE_ITEM, FIRE_STONE, FLAREON
	db EVOLVE_HAPPINESS, TR_MORNDAY, ESPEON
	db EVOLVE_ITEM, SUN_STONE, ESPEON
	db EVOLVE_HAPPINESS, TR_NITE, UMBREON
	db EVOLVE_ITEM, MOON_STONE, UMBREON
	db EVOLVE_ITEM, ICE_STONE, GLACEON
	db EVOLVE_ITEM, LEAF_STONE, LEAFEON
	db EVOLVE_ITEM, SHINY_STONE, SYLVEON
	db EVOLVE_ITEM, DAWN_STONE, MEOWTH
	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, TACKLE
	db 4, SAND_ATTACK
	db 7, QUICK_ATTACK
	db 10, SWIFT
	db 13, BITE
	db 16, CHARM
	db 50, HYPER_BEAM
	db 50, DOUBLE_EDGE
	db 0 ; no more level-up moves
