	db EVOLVE_LEVEL, 16, IVYSAUR
	db EVOLVE_ITEM, LEAF_STONE, TREECKO
	db EVOLVE_ITEM, SUN_STONE, TURTWIG
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, GROWL
	db 4, VINE_WHIP
	db 7, ACID
	db 10, LEECH_SEED
	db 13, RAZOR_LEAF
	db 15, POISONPOWDER
	db 15, SLEEP_POWDER
	db 19, GROWTH
	db 22, SEED_BOMB
	db 25, SYNTHESIS
	db 28, SLEEP_POWDER
	db 31, LEECH_SEED
	db 34, ENERGY_BALL
	db 37, SLUDGE_BOMB
	db 40, GROWTH
	db 43, LEECH_SEED
	db 46, SLEEP_POWDER
	db 49, ENERGY_BALL
	db 52, SLUDGE_BOMB
	db 0 ; no more level-up moves

