	db EVOLVE_LEVEL, 22, SWELLOW
	db 0 ; no more evolutions
	db 1, GROWL
	db 1, PECK
	db 4, PURSUIT
	db 7, QUICK_ATTACK
	db 10, WING_ATTACK
	db 13, DOUBLE_TEAM
	db 16, PURSUIT
	db 19, WING_ATTACK
	db 20, FALSE_SWIPE
	db 22, GROWL
	db 25, PURSUIT
	db 28, QUICK_ATTACK
	db 30, FALSE_SWIPE
	db 31, AERIAL_ACE
	db 34, DOUBLE_TEAM
	db 37, RETURN
	db 40, SKY_ATTACK
	db 40, FALSE_SWIPE
	db 43, AERIAL_ACE
	db 46, DOUBLE_TEAM
	db 49, RETURN
	db 52, SKY_ATTACK
	db 0 ; no more level-up moves
