	db EVOLVE_ITEM, SHINY_STONE, KECLEON
	db 0 ; no more evolutions
	db 1, DEFENSE_CURL
	db 1, SCRATCH
	db 4, FURY_SWIPES
	db 7, QUICK_ATTACK
	db 10, FALSE_SWIPE
	db 13, AMNESIA
	db 16, CHARM
	db 19, SWIFT
	db 22, FURY_ATTACK
	db 25, FALSE_SWIPE
	db 28, QUICK_ATTACK
	db 31, BODY_SLAM
	db 34, NIGHT_SLASH
	db 37, RETURN
	db 40, FALSE_SWIPE
	db 43, QUICK_ATTACK
	db 46, BODY_SLAM
	db 49, NIGHT_SLASH
	db 52, DOUBLE_EDGE
	db 0 ; no more level-up moves
