	db 0 ; no more evolutions
	db 1, NIGHT_SHADE
	db 1, LEECH_LIFE
	db 4, SHARPEN
	db 7, SCARY_FACE
	db 10, FURY_SWIPES
	db 13, NIGHT_SHADE
	db 16, LEECH_LIFE
	db 19, SHARPEN
	db 22, SWORDS_DANCE
	db 25, SHADOW_CLAW
	db 28, NIGHT_SLASH
	db 31, SWORDS_DANCE
	db 34, NIGHT_SHADE
	db 37, PIN_MISSILE
	db 40, SHADOW_CLAW
	db 43, SWORDS_DANCE
	db 46, NIGHT_SHADE
	db 49, PIN_MISSILE
	db 52, SHADOW_CLAW
	db 0 ; no more level-up moves
