	db EVOLVE_HAPPINESS, TR_ANYTIME, LOPUNNY
	db 0 ; no more evolutions
	db 1, MIRROR_COAT
	db 1, MAGIC_COAT
	db 1, POUND
	db 1, DEFENSE_CURL
	db 1, LOW_KICK
	db 12, KARATE_CHOP
	db 16, QUICK_ATTACK
	db 20, DOUBLE_KICK
	db 24, SEISMIC_TOSS
	db 28, DRAIN_PUNCH
	db 32, HEADBUTT
	db 36, AGILITY
	db 40, DYNAMIC_PUNCH
	db 44, FLATTER
	db 48, BOUNCE
	db 52, HEALING_WISH
	db 56, HI_JUMP_KICK
	db 0 ; no more level-up moves