	db EVOLVE_LEVEL, 24, PRIMEAPE
	db 0 ; no more evolutions
	db 1, LEER
	db 1, SCRATCH
	db 4, LOW_KICK
	db 7, FURY_SWIPES
	db 10, KARATE_CHOP
	db 10, FALSE_SWIPE
	db 13, HEADBUTT
	db 16, DOUBLE_KICK
	db 19, SCREECH
	db 20, FALSE_SWIPE
	db 22, SEISMIC_TOSS
	db 25, HEADBUTT
	db 28, CROSS_CHOP
	db 30, FALSE_SWIPE
	db 31, STRENGTH
	db 34, JUMP_KICK
	db 37, MEGA_KICK
	db 40, CROSS_CHOP
	db 40, FALSE_SWIPE
	db 43, HI_JUMP_KICK
	db 46, SCREECH
	db 49, MEGA_KICK
	db 52, JUMP_KICK
	db 0 ; no more level-up moves
