	db EVOLVE_ITEM, DUSK_STONE, MIMIKYU
	db EVOLVE_ITEM, DAWN_STONE, RAIKOU
	db 0 ; no more evolutions
	db 1, GROWL
	db 1, QUICK_ATTACK
	db 4, THUNDERSHOCK
	db 7, CHARM
	db 10, THUNDERWAVE
	db 13, SAND_ATTACK
	db 16, SHOCK_WAVE
	db 19, CHARM
	db 22, DAZZLING_GLEAM
	db 25, SHOCK_WAVE
	db 28, THUNDERWAVE
	db 31, QUICK_ATTACK
	db 34, DAZZLING_GLEAM
	db 37, NASTY_PLOT
	db 40, COPYCAT
	db 43, SWIFT
	db 46, ENTRAINMENT
	db 49, AGILITY
	db 52, THUNDER
	db 0 ; no more level-up moves
