	db 0 ; no more evolutions
	db 1, FAIRY_WIND
	db 1, CONFUSION
	db 4, GROWL
	db 7, DOUBLE_TEAM
	db 10, HYPNOSIS
	db 13, DRAINING_KISS
	db 16, TELEPORT
	db 19, PSYBEAM
	db 22, CHARM
	db 25, DOUBLE_TEAM
	db 28, DRAINING_KISS
	db 31, HYPNOSIS
	db 34, CONFUSION
	db 37, PSYCHIC
	db 40, WISH
	db 43, HYPNOSIS
	db 46, PSYBEAM
	db 49, DREAM_EATER
	db 52, DAZZLING_GLEAM
	db 58, HEAL_PULSE
	db 62, FUTURE_SIGHT
	db 0 ; no more level-up moves
