	db 0 ; no more evolutions
	db 1, AURA_SPHERE
	db 1, BARRIER
	db 1, AMNESIA
	db 11, SHADOW_BALL
	db 22, PSYBEAM
	db 33, PSYCH_UP
	db 44, PSYCHIC
	db 51, SHADOW_BALL
	db 51, AURA_SPHERE
	db 51, RECOVER
	db 51, PSYCHIC
	db 56, POWER_SWAP
	db 60, PSYSTRIKE
	db 64, PSYBEAM
	db 68, FUTURE_SIGHT
	db 70, AURA_SPHERE