	db EVOLVE_ITEM, DUSK_STONE, WEAVILE
	db EVOLVE_ITEM, SHINY_STONE, MEOWTH
	db 1, LEER
	db 1, SCRATCH
	db 4, QUICK_ATTACK
	db 7, METAL_CLAW
	db 10, FEINT_ATTACK
	db 13, SHARPEN
	db 16, QUICK_ATTACK
	db 19, METAL_CLAW
	db 22, FEINT_ATTACK
	db 25, ICE_PUNCH
	db 28, FALSE_SWIPE
	db 31, SWORDS_DANCE
	db 34, ICE_PUNCH
	db 37, AERIAL_ACE
	db 40, FALSE_SWIPE
	db 43, QUICK_ATTACK
	db 46, SWORDS_DANCE
	db 49, NIGHT_SLASH
	db 52, ICE_PUNCH
	db 0 ; no more level-up moves
