	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, THUNDERSHOCK
	db 4, SAND_ATTACK
	db 7, QUICK_ATTACK
	db 10, SWIFT
	db 13, BITE
	db 16, CHARM
	db 19, SHOCK_WAVE
	db 22, THUNDERSHOCK
	db 25, THUNDERWAVE
	db 28, DISCHARGE
	db 31, DOUBLE_KICK
	db 34, THUNDER_FANG
	db 37, PIN_MISSLE
	db 40, THUNDERWAVE
	db 43, THUNDERBOLT
	db 46, DOUBLE_KICK
	db 49, HYPER_VOICE
	db 52, THUNDER
	db 0 ; no more level-up moves
