	db EVOLVE_ITEM, FIRE_STONE, ENTEI
	db 0 ; no more evolutions
	db 1, SMOG
	db 1, EMBER
	db 4, WITHDRAW
	db 7, RAPID_SPIN
	db 10, SMOKESCREEN
	db 13, FLAME_WHEEL
	db 16, BODY_SLAM
	db 19, CURSE
	db 22, AMNESIA
	db 25, ANCIENTPOWER
	db 28, IRON_DEFENSE
	db 31, FLAME_WHEEL
	db 34, BODY_SLAM
	db 37, FLAMETHROWER
	db 40, CURSE
	db 43, ANCIENTPOWER
	db 46, BODY_SLAM
	db 49, FLAMETHROWER
	db 52, CURSE
	db 0 ; no more level-up moves
