	db EVOLVE_ITEM, THUNDERSTONE, ZAPDOS
	db 0 ; no more evolutions
	db 1, THUNDERSHOCK
	db 1, GROWL
	db 4, TAIL_WHIP
	db 7, FAIRY_WIND
	db 10, SPARK
	db 13, QUICK_ATTACK
	db 16, DOUBLE_TEAM
	db 19, SWIFT
	db 22, THUNDERWAVE
	db 25, THUNDERBOLT
	db 28, THUNDERPUNCH
	db 31, FAIRY_WIND
	db 34, SLAM
	db 37, PLAY_ROUGH
	db 40, ELECTRO_BALL
	db 43, NASTY_PLOT
	db 46, AGILITY
	db 49, DISCHARGE
	db 52, THUNDER
	db 0 ; no more level-up moves
