	db EVOLVE_LEVEL, 32, MAGNETON
	db 0 ; no more evolutions
	db 1, THUNDERSHOCK
	db 1, SCREECH
	db 4, SUPERSONIC
	db 7, THUNDERWAVE
	db 10, SWIFT
	db 13, IRON_DEFENSE
	db 16, SHOCK_WAVE
	db 19, THUNDERWAVE
	db 22, FLASH_CANNON
	db 25, SHOCK_WAVE
	db 28, THUNDERWAVE
	db 31, TRI_ATTACK
	db 34, THUNDERBOLT
	db 37, FLASH_CANNON
	db 40, SWIFT
	db 43, THUNDERWAVE
	db 46, TRI_ATTACK
	db 49, THUNDERBOLT
	db 52, FLASH_CANNON
	db 0 ; no more level-up moves
