	db EVOLVE_LEVEL, 24, PARASECT
	db 0 ; no more evolutions
	db 1, SCRATCH
	db 1, SLEEP_POWDER
	db 4, VINE_WHIP
	db 7, LEECH_LIFE
	db 10, POISON_POWDER
	db 10, FALSE_SWIPE
	db 13, VINE_WHIP
	db 16, SPORE
	db 19, SLASH
	db 20, FALSE_SWIPE
	db 22, RAZOR_LEAF
	db 25, ROCK_THROW
	db 28, LEECH_LIFE
	db 30, FALSE_SWIPE
	db 31, SPORE
	db 34, SEED_BOMB
	db 37, TOXIC
	db 40, FALSE_SWIPE
	db 43, ROCK_THROW
	db 46, PIN_MISSILE
	db 49, SEED_BOMB
	db 52, SPORE
	db 0 ; no more level-up moves
