	db EVOLVE_ITEM, SHINY_STONE, SUCCINE
	db 0 ; no more evolutions
	db 1, LEER
	db 1, WRAP
	db 4, TWISTER
	db 7, THUNDERWAVE
	db 10, SLAM
	db 13, SAFEGUARD
	db 16, AQUA_JET
	db 19, SHARPEN
	db 22, DRAGONBREATH
	db 25, TWISTER
	db 28, SAFEGUARD
	db 31, THUNDERWAVE
	db 34, SHARPEN
	db 37, DRAGONBREATH
	db 40, DRAGON_CLAW
	db 43, THUNDERWAVE
	db 46, WING_ATTACK
	db 49, HYPER_BEAM
	db 52, SHARPEN
	db 55, THUNDER
	db 58, WING_ATTACK
	db 61, HYPER_BEAM
	db 64, OUTRAGE	
	db 0 ; no more level-up moves
