	db 0 ; no more evolutions
	db 1, GROWL
	db 1, TACKLE
	db 4, THUNDERSHOCK
	db 7, CONFUSE_RAY
	db 10, GLARE
	db 13, LIGHT_SCREEN
	db 16, SWIFT
	db 19, THUNDERSHOCK
	db 22, POWER_GEM
	db 25, SHOCK_WAVE
	db 28, SWIFT
	db 31, DRAGONBREATH
	db 34, THUNDERBOLT
	db 37, POWER_GEM
	db 40, GLARE
	db 43, DRAGON_PULSE
	db 46, THUNDERBOLT
	db 49, POWER_GEM
	db 52, THUNDER
	db 0 ; no more level-up moves
