	db 0 ; no more evolutions
	db 1, WING_ATTACK
	db 1, ROCK_THROW
	db 4, SCARY_FACE
	db 7, ANCIENTPOWER
	db 10, BITE
	db 13, WING_ATTACK
	db 16, ROCK_THROW
	db 19, ANCIENTPOWER
	db 22, ROCK_THROW
	db 25, SCARY_FACE
	db 28, CRUNCH
	db 31, EARTHQUAKE
	db 34, WING_ATTACK
	db 37, ROCK_SLIDE
	db 40, SKY_ATTACK
	db 43, CRUNCH
	db 46, EARTHQUAKE
	db 49, WING_ATTACK
	db 52, ROCK_SLIDE
	db 0 ; no more level-up moves
