	db EVOLVE_LEVEL, 30, GLALIE
	db EVOLVE_ITEM, ICE_STONE, FROSLASS
	db 0 ; no more evolutions
	db 1, ASTONISH
	db 1, POWDER_SNOW
	db 4, TACKLE
	db 7, LEER
	db 10, DOUBLE_TEAM
	db 13, ICY_WIND
	db 16, SWIFT
	db 19, HEADBUTT
	db 22, BITE
	db 25, ICE_PUNCH
	db 28, ICY_WIND
	db 31, HEADBUTT
	db 34, CRUNCH
	db 37, ICE_PUNCH
	db 40, DOUBLE_TEAM
	db 43, AURORA_BEAM
	db 46, HEADBUTT
	db 49, CRUNCH
	db 52, BLIZZARD
	db 0 ; no more level-up moves
