	db EVOLVE_HAPPINESS, TR_ANYTIME, PIKACHU
	db EVOLVE_LEVEL, 20, PIKACHU
	db EVOLVE_ITEM, DUSK_STONE, MIMIKYU
	db EVOLVE_ITEM, THUNDERSTONE, ELEKID
	db 0 ; no more evolutions
	db 1, THUNDERSHOCK
	db 1, GROWL
	db 4, TAIL_WHIP
	db 7, FAIRY_WIND
	db 10, SPARK
	db 13, QUICK_ATTACK
	db 16, DOUBLE_TEAM
	db 19, SWIFT
	db 22, THUNDERWAVE
	db 25, THUNDERBOLT
	db 28, THUNDERPUNCH
	db 31, FAIRY_WIND
	db 34, THUNDERWAVE
	db 37, PLAY_ROUGH
	db 40, THUNDERBOLT
	db 43, NASTY_PLOT
	db 46, THUNDERWAVE
	db 49, PLAY_ROUGH
	db 52, THUNDERBOLT
	db 0 ; no more level-up moves
