	db EVOLVE_LEVEL, 30, BASTIODON
	db 0 ; no more evolutions
	db 1, CURSE
	db 1, METAL_CLAW
	db 4, TACKLE
	db 7, ANCIENTPOWER
	db 10, IRON_DEFENSE
	db 13, CURSE
	db 16, METAL_CLAW
	db 19, HEADBUTT
	db 22, SCARY_FACE
	db 25, IRON_DEFENSE
	db 28, DIG
	db 31, BODY_SLAM
	db 34, IRON_HEAD
	db 37, ANCIENTPOWER
	db 40, DOUBLE_EDGE
	db 43, ENDURE
	db 46, METAL_BURST
	db 49, IRON_HEAD
	db 52, HEAVY_SLAM
	db 0 ; no more level-up moves
