	db EVOLVE_LEVEL, 27, JUMPLUFF
	db 0 ; no more evolutions
	db 1, GUST
	db 1, ABSORB
	db 4, GROWTH
	db 7, VINE_WHIP
	db 10, POISON_POWDER
	db 13, STUN_SPORE
	db 16, SYNTHESIS
	db 19, AIR_CUTTER
	db 22, GROWTH
	db 25, MEGA_DRAIN
	db 28, LEECH_SEED
	db 31, AIR_SLASH
	db 34, GIGA_DRAIN
	db 37, STUN_SPORE
	db 40, LEECH_SEED
	db 43, GIGA_DRAIN
	db 46, AIR_SLASH
	db 49, STUN_SPORE
	db 52, LEECH_SEED
	db 0 ; no more level-up moves
