	db EVOLVE_LEVEL, 16, BAYLEEF
	db EVOLVE_ITEM, LEAF_STONE, TURTWIG
	db EVOLVE_ITEM, SUN_STONE, TREECKO
	db 1, GROWL
	db 1, TACKLE
	db 4, VINE_WHIP
	db 7, POISON_POWDER
	db 10, SYNTHESIS
	db 13, RAZOR_LEAF
	db 16, REFLECT
	db 19, SYNTHESIS
	db 22, BODY_SLAM
	db 25, LIGHT_SCREEN
	db 28, POISON_POWDER
	db 31, PLAY_ROUGH
	db 34, BODY_SLAM
	db 37, RAZOR_LEAF
	db 40, SYNTHESIS
	db 43, LIGHT_SCREEN
	db 46, REFLECT
	db 49, SEED_BOMB
	db 52, SOLARBEAM
	db 0 ; no more level-up moves
