	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, BONE_CLUB
	db 4, GROWL
	db 7, HEADBUTT
	db 10, ROCK_THROW
	db 10, FALSE_SWIPE
	db 13, BONE_CLUB
	db 16, FALSE_SWIPE
	db 19, HEADBUTT
	db 20, FALSE_SWIPE
	db 22, BONEMERANG
	db 25, SWORDS_DANCE
	db 28, FALSE_SWIPE
	db 31, BONE_RUSH
	db 34, RETURN
	db 37, SWORDS_DANCE
	db 40, BONEMERANG
	db 40, FALSE_SWIPE
	db 43, BONE_RUSH
	db 46, THRASH
	db 49, ENDEAVOR
	db 52, STOMPING_TANTRUM
	db 0 ; no more level-up moves