	db EVOLVE_LEVEL, 18, AZUMARILL
	db 0 ; no more evolutions
	db 1, SPLASH
	db 1, BUBBLE
	db 4, TAIL_WHIP
	db 7, WATER_GUN
	db 10, SLAM
	db 13, DEFENSE_CURL
	db 13, ROLLOUT
	db 16, AQUA_JET
	db 19, PLAY_ROUGH
	db 22, BUBBLEBEAM
	db 25, CHARM
	db 28, PLAY_ROUGH
	db 31, AQUA_JET
	db 34, DOUBLE_EDGE
	db 37, WATERFALL
	db 40, PLAY_ROUGH
	db 43, AQUA_JET
	db 46, DOUBLE_EDGE
	db 49, WATERFALL
	db 52, PLAY_ROUGH
	db 0 ; no more level-up moves
