	db 0 ; no more evolutions
	db 1, SCARY_FACE
	db 1, WATER_GUN
	db 4, THUNDERSHOCK
	db 7, POWDERSNOW
	db 10, AQUA_JET
	db 13, CALM_MIND
	db 16, BUBBLEBEAM
	db 19, CALM_MIND
	db 22, BODY_SLAM
	db 25, SHOCK_WAVE
	db 28, ICY_WIND
	db 31, WATERFALL
	db 31, SURF
	db 34, AURORA_BEAM
	db 37, CALM_MIND
	db 40, ANCIENTPOWER
	db 43, THUNDERBOLT
	db 43, ICE_BEAM
	db 46, WATERFALL
	db 46, SURF
	db 49, THUNDER
	db 52, HYDRO_PUMP
	db 0 ; no more level-up moves