	db EVOLVE_LEVEL, 25, RIBOMBEE
	db 0 ; no more evolutions
	db 1, ABSORB
	db 1, FAIRY_WIND
	db 4, STUN_SPORE
	db 7, SWEET_SCENT
	db 10, STRUGGLE_BUG
	db 13, DRAINING_KISS
	db 16, CHARM
	db 19, STUN_SPORE
	db 22, SWEET_SCENT
	db 25, STRUGGLE_BUG
	db 28, DRAINING_KISS
	db 31, CHARM
	db 34, BUG_BUZZ
	db 37, DAZZLING_GLEAM
	db 40, STRUGGLE_BUG
	db 43, DRAINING_KISS
	db 46, STUN_SPORE
	db 49, BUG_BUZZ
	db 52, DAZZLING_GLEAM
	db 0 ; no more level-up moves
