	db EVOLVE_LEVEL, 28, SEADRA
	db 0 ; no more evolutions
	db 1, BUBBLE
	db 1, LEER
	db 4, SMOKESCREEN
	db 7, TWISTER
	db 10, WATER_GUN
	db 13, LEER
	db 16, SMOKESCREEN
	db 19, SWIFT
	db 22, ATTRACT
	db 25, BUBBLEBEAM
	db 28, DRAGON_PULSE
	db 31, SWIFT
	db 34, ATTRACT
	db 37, BUBBLEBEAM
	db 40, DRAGON_PULSE
	db 43, SWIFT
	db 46, ATTRACT
	db 49, BUBBLEBEAM
	db 52, DRAGON_PULSE
	db 0 ; no more level-up moves
