	db EVOLVE_ITEM, SHINY_STONE, ALAKAZAM
	db EVOLVE_LEVEL, 40, ALAKAZAM
	db 0 ; no more evolutions
	db 1, TELEPORT
	db 1, CONFUSION
	db 16, PSYBEAM
	db 20, RECOVER
	db 22, HYPNOSIS
	db 25, PSYBEAM
	db 28, PSYCHO_CUT
	db 31, SHADOW_BALL
	db 34, CALM_MIND
	db 37, DREAM_EATER
	db 40, PSYCH_UP
	db 43, LIGHT_SCREEN
	db 46, RECOVER
	db 49, AURA_SPHERE
	db 52, PSYCHIC
	db 0 ; no more level-up moves