	db EVOLVE_ITEM, DUSK_STONE, MISMAGIUS
	db 0 ; no more evolutions
	db 1, CONFUSION
	db 1, FAIRY_WIND
	db 4, ASTONISH
	db 7, CONFUSE_RAY
	db 10, CONFUSION
	db 13, FAIRY_WIND
	db 16, NIGHT_SHADE
	db 19, PSYBEAM
	db 22, MEAN_LOOK
	db 25, DAZZLING_GLEAM
	db 30, SHADOW_BALL
	db 37, PSYCHIC
	db 43, HEX
	db 48, PERISH_SONG
	db 52, SHADOW_SNEAK
	db 0 ; no more level-up moves
