	db EVOLVE_LEVEL, 22, SANDSLASH
	db 0 ; no more evolutions
	db 1, SAND_ATTACK
	db 1, SCRATCH
	db 1, DEFENSE_CURL
	db 9, ROLLOUT
	db 10, FALSE_SWIPE
	db 11, DIG
	db 13, FURY_SWIPES
	db 15, RAPID_SPIN
	db 17, HORN_ATTACK
	db 19, FALSE_SWIPE
	db 22, DIG
	db 22, SLASH
	db 24, BODY_SLAM
	db 30, EARTHQUAKE
	db 30, FALSE_SWIPE
	db 32, POISON_JAB
	db 34, ROLLOUT
	db 36, DEFENSE_CURL
	db 38, BODY_SLAM
	db 40, EARTHQUAKE
	db 40, FALSE_SWIPE
	db 42, SLASH
	db 0 ; no more level-up moves
