	db EVOLVE_LEVEL, 28, NOIVERN
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, ABSORB
	db 4, GUST
	db 8, SUPERSONIC
	db 12, DOUBLE_TEAM
	db 16, WING_ATTACK
	db 20, BITE
	db 24, AIR_CUTTER
	db 28, DRAGON_PULSE
	db 32, HYPER_VOICE
	db 36, AIR_SLASH
	db 40, SCREECH
	db 44, MOONLIGHT
	db 48, DRAGON_PULSE
	db 52, AIR_SLASH
	db 56, HYPER_VOICE
	db 60, DRAGON_PULSE
	db 64, AIR_SLASH
	db 68, HYPER_VOICE
	db 0 ; no more level-up moves

