	db EVOLVE_LEVEL, 30, YANMEGA
	db 0 ; no more evolutions
	db 1, QUICK_ATTACK
	db 1, DOUBLE_TEAM
	db 4, STRUGGLE_BUG
	db 7, GUST
	db 10, SILVER_WIND
	db 13, AIR_CUTTER
	db 16, QUICK_ATTACK
	db 19, DRAGON_RAGE
	db 22, SIGNAL_BEAM
	db 25, AIR_CUTTER
	db 28, DRAGON_RAGE
	db 31, DRAGONBREATH
	db 34, AIR_SLASH
	db 37, BUG_BUZZ
	db 40, HYPNOSIS
	db 43, DRAGON_RAGE
	db 46, DRAGON_PULSE
	db 49, AIR_SLASH
	db 52, BUG_BUZZ
	db 0 ; no more level-up moves
