	db EVOLVE_ITEM, LEAF_STONE, EXEGGUTOR
	db EVOLVE_ITEM, SHINY_STONE, AEXEGGUTOR
	db 0 ; no more evolutions
	db 1, HYPNOSIS
	db 1, ABSORB
	db 4, CONFUSION
	db 7, LEECH_SEED
	db 10, REFLECT
	db 13, SYNTHESIS
	db 16, MEGA_DRAIN
	db 19, PSYBEAM
	db 22, EXTRASENSORY
	db 25, SYNTHESIS
	db 28, CONFUSION
	db 31, HYPNOSIS
	db 34, BULLET_SEED
	db 37, GIGA_DRAIN
	db 40, PSYCHIC
	db 43, UPROAR
	db 46, SOLARBEAM
	db 49, GIGA_DRAIN
	db 52, PSYCHIC
	db 0 ; no more level-up moves
