	db EVOLVE_LEVEL, 34, GABITE
	db 0 ; no more evolutions
	db 1, SAND_ATTACK
	db 1, BITE
	db 4, SCRATCH
	db 7, METAL_CLAW
	db 10, SHARPEN
	db 13, DRAGONBREATH
	db 16, BITE
	db 19, DIG
	db 22, THRASH
	db 25, SHARPEN
	db 28, DIG
	db 30, FALSE_SWIPE
	db 31, METAL_CLAW
	db 34, DRAGON_CLAW
	db 37, EARTHQUAKE
	db 40, SHARPEN
	db 40, FALSE_SWIPE
	db 43, THRASH
	db 46, IRON_HEAD
	db 49, OUTRAGE
	db 50, FALSE_SWIPE
	db 52, EARTHQUAKE
	db 0 ; no more level-up moves

