	db EVOLVE_ITEM, FIRE_STONE, MAGMORTAR
	db 0 ; no more evolutions
	db 1, THUNDERSHOCK
	db 1, ROCK_SMASH
	db 4, LIGHT_SCREEN
	db 7, THUNDERSHOCK
	db 10, ROCK_SMASH
	db 13, SCREECH
	db 16, SHOCK_WAVE
	db 19, KARATE_CHOP
	db 22, THUNDERPUNCH
	db 25, LOW_KICK
	db 28, GLARE
	db 31, THUNDERBOLT
	db 34, DRAIN_PUNCH
	db 37, THUNDERPUNCH
	db 40, GLARE
	db 43, SCREECH
	db 46, THUNDERBOLT
	db 49, DRAIN_PUNCH
	db 52, THUNDERPUNCH
	db 0 ; no more level-up moves
