	db EVOLVE_LEVEL, 30, CRAWDAUNT
	db 0 ; no more evolutions
	db 1, SHARPEN
	db 1, SCRATCH
	db 4, WATER_GUN
	db 7, LEER
	db 10, DOUBLE_HIT
	db 13, BITE
	db 16, IRON_DEFENSE
	db 19, SLASH
	db 20, FALSE_SWIPE
	db 22, METAL_CLAW
	db 25, CRABHAMMER
	db 28, AQUA_JET
	db 30, FALSE_SWIPE
	db 31, SHARPEN
	db 34, NIGHT_SLASH
	db 37, CRABHAMMER
	db 40, METAL_CLAW
	db 40, FALSE_SWIPE
	db 43, AQUA_JET
	db 46, SWORDS_DANCE
	db 49, CRUNCH
	db 52, CRABHAMMER
	db 0 ; no more level-up moves
