	db EVOLVE_LEVEL, 20, MAGCARGO
	db 0 ; no more evolutions
	db 1, SMOG
	db 1, EMBER
	db 4, HARDEN
	db 7, ROCK_THROW
	db 10, IRON_DEFENSE
	db 13, AMNESIA
	db 16, FIRE_SPIN
	db 19, ANCIENTPOWER
	db 22, EMBER
	db 25, IRON_DEFENSE
	db 28, FIRE_SPIN
	db 31, EARTH_POWER
	db 34, RECOVER
	db 37, POWER_GEM
	db 40, FLAMETHROWER
	db 43, EARTH_POWER
	db 46, RECOVER
	db 49, POWER_GEM
	db 52, FLAMETHROWER
	db 0 ; no more level-up moves
