	db EVOLVE_LEVEL, 32, VENOMOTH
	db 0 ; no more evolutions
	db 1, STRUGGLE_BUG
	db 1, CONFUSION
	db 4, TACKLE
	db 7, SUPERSONIC
	db 10, DISABLE
	db 13, SILVER_WIND
	db 16, POISON_POWDER
	db 19, PSYBEAM
	db 22, SIGNAL_BEAM
	db 25, ZEN_HEADBUTT
	db 28, POISON_POWDER
	db 31, SLEEP_POWDER
	db 34, PSYCHIC
	db 37, PSYBEAM
	db 40, CONFUSE_RAY
	db 43, POISON_FANG
	db 48, QUIVER_DANCE
	db 52, BUG_BUZZ
	db 0 ; no more level-up moves