	db 0 ; no more evolutions
	db 1, SCRATCH
	db 4, GROWL
	db 6, EMBER
	db 8, SMOKESCREEN
	db 11, DRAGONBREATH
	db 14, SLASH
	db 16, FLAME_WHEEL
	db 19, BITE
	db 22, WILL_O_WISP
	db 25, FIRE_PUNCH
	db 28, FLAMETHROWER
	db 32, FIRE_SPIN
	db 36, WING_ATTACK
	db 40, FIRE_BLAST
	db 44, AIR_SLASH
	db 44, DRAGONBREATH
	db 48, ANCIENTPOWER
	db 48, FLAMETHROWER
	db 52, DRAGON_CLAW
	db 52, WILL_O_WISP
	db 56, DRAGON_PULSE
	db 60, AIR_SLASH
	db 64, FIRE_BLAST
	db 0 ; no more level-up moves
