	db EVOLVE_ITEM, SHINY_STONE, KYOGRE
	db 0 ; no more evolutions
	db 1, GROWL
	db 1, WATER_GUN
	db 4, SING
	db 7, SAFEGUARD
	db 10, TACKLE
	db 13, CONFUSE_RAY
	db 16, ICE_SHARD
	db 19, SING
	db 22, WATER_GUN
	db 25, ICY_WIND
	db 28, CONFUSE_RAY
	db 31, SURF
	db 34, BUBBLEBEAM
	db 37, ICE_BEAM
	db 40, SAFEGUARD
	db 43, FREEZE_DRY
	db 46, BODY_SLAM
	db 49, HYDRO_PUMP
	db 52, BLIZZARD
	db 55, SHEER_COLD
	db 58, PERISH_SONG
	db 60, HYPER_BEAM
	db 0 ; no more level-up moves
