	db EVOLVE_ITEM, FIRE_STONE, NINETALES
	db 1, TAIL_WHIP
	db 1, EMBER
	db 7, QUICK_ATTACK
	db 10, CONFUSE_RAY
	db 13, PSYBEAM
	db 16, WILL_O_WISP
	db 19, CHARM
	db 22, FLAMETHROWER
	db 25, PSYCHIC
	db 28, FIRE_SPIN
	db 31, SAFEGUARD
	db 34, CONFUSE_RAY
	db 37, CHARM
	db 40, WILL_O_WISP
	db 43, PSYCHIC
	db 46, FLAMETHROWER
	db 49, IMPRISON
	db 52, FIRE BLAST
	db 58, iNFERNO
	db 0 ; no more level-up moves
