	db EVOLVE_ITEM, SUN_STONE, JIRACHI
	db EVOLVE_ITEM, MOON_STONE, MEW
	db 0 ; no more evolutions
	db 1, LEER
	db 1, SCRATCH
	db 4, ASTONISH
	db 7, PURSUIT
	db 10, CONFUSE_RAY
	db 13, DISABLE
	db 16, NIGHT_SHADE
	db 19, BITE
	db 22, FURY_SWIPES
	db 25, POWER_GEM
	db 28, SHADOW_CLAW
	db 31, NIGHT_SLASH
	db 34, SHADOW_BALL
	db 37, CONFUSE_RAY
	db 40, POWER_GEM
	db 43, NIGHT_SHADE
	db 46, ZEN_HEADBUTT
	db 49, NIGHT_SLASH
	db 52, SHADOW_CLAW
	db 0 ; no more level-up moves
