	db EVOLVE_LEVEL, 14, QUILAVA
	db EVOLVE_ITEM, FIRE_STONE, CHIMCHAR
	db 1, TACKLE
	db 1, LEER
	db 4, SMOKESCREEN
	db 7, EMBER
	db 10, SWIFT
	db 13, FIRE_SPIN
	db 16, DEFENSE_CURL
	db 19, FLAME_WHEEL
	db 22, QUICK_ATTACK
	db 25, SWIFT
	db 28, FLAMETHROWER
	db 31, DEFENSE_CURL
	db 34, ENERGY_BALL
	db 37, SWIFT
	db 40, FLAMETHROWER
	db 43, DEFENSE_CURL
	db 46, SWIFT
	db 49, ENERGY_BALL
	db 52, FLAMETHROWER
	db 0 ; no more level-up moves
