	db EVOLVE_LEVEL, 36, BLAZIKEN
	db 0 ; no more evolutions
	db 1, SCRATCH
	db 1, GROWL
	db 4, EMBER
	db 7, QUICK_ATTACK
	db 10, PECK
	db 13, RETURN
	db 16, DOUBLE_KICK
	db 19, FLAME_WHEEL
	db 22, SLASH
	db 25, SAND_ATTACK
	db 28, FIRE_SPIN
	db 31, AERIAL_ACE
	db 34, FLAME_WHEEL
	db 37, JUMP_KICK
	db 40, AURA_SPHERE
	db 43, FLAMETHROWER
	db 46, AERIAL_ACE
	db 49, FIRE_PUNCH
	db 52, HI_JUMP_KICK
	db 0 ; no more level-up moves