	db EVOLVE_LEVEL, 24, MACHOKE
	db EVOLVE_ITEM, SHINY_STONE, ABRA
	db 1, LEER
	db 1, LOW_KICK
	db 4, KARATE_CHOP
	db 7, SEISMIC_TOSS
	db 10, SCARY_FACE
	db 13, ROCK_THROW
	db 16, KARATE_CHOP
	db 19, LEER
	db 22, CROSS_CHOP
	db 25, ROCK_THROW
	db 28, SEISMIC_TOSS
	db 31, SCARY_FACE
	db 34, CROSS_CHOP
	db 37, ROCK_THROW
	db 40, LEER
	db 43, SEISMIC_TOSS
	db 46, STRENGTH
	db 49, ROCK_THROW
	db 52, CROSS_CHOP
	db 0 ; no more level-up moves
