	db EVOLVE_ITEM, MOON_STONE, NIDOKING
	db 1, LEER
	db 1, SCRATCH
	db 4, POISON_STING
	db 8, DOUBLE_KICK
	db 10, FURY_SWIPES
	db 13, HORN_ATTACK
	db 16, SLUDGE
	db 19, MUD_SLAP
	db 22, POISON_JAB
	db 25, EARTHQUAKE
	db 34, TOXIC
	db 37, POISON_JAB
	db 40, EARTHQUAKE
	db 49, POISON_JAB
	db 52, EARTHQUAKE
	db 0 ; no more level-up moves
