	db EVOLVE_LEVEL, 25, OCTILLERY
	db 0 ; no more evolutions
	db 1, WATER_GUN
	db 1, EMBER
	db 4, SMOKESCREEN
	db 7, GROWTH
	db 10, PSYBEAM
	db 13, SMOKESCREEN
	db 16, WATER_GUN
	db 19, EMBER
	db 22, GROWTH
	db 25, OCTAZOOKA
	db 28, PSYBEAM
	db 31, BUBBLEBEAM
	db 31, FLAMETHROWER
	db 34, GROWTH
	db 37, AURORA_BEAM
	db 37, SIGNAL_BEAM
	db 37, PSYBEAM
	db 40, OCTAZOOKA
	db 43, GROWTH
	db 46, BUBBLEBEAM
	db 46, FLAMETHROWER
	db 49, HYDRO_PUMP
	db 52, FIRE_BLAST
	db 52, BUBBLEBEAM
	db 52, FLAMETHROWER
	db 52, SIGNAL_BEAM
	db 52, AURORA_BEAM
	db 0 ; no more level-up moves
