	db EVOLVE_LEVEL, 16, WARTORTLE
	db EVOLVE_ITEM, WATER_STONE, MUDKIP
	db EVOLVE_ITEM, ICE_STONE, PIPLUP
	db 1, TACKLE
	db 4, WITHDRAW
	db 6, WATER_GUN
	db 8, IRON_DEFENSE
	db 11, BITE
	db 14, BUBBLEBEAM
	db 16, AQUA_JET
	db 19, RAPID_SPIN
	db 22, FALSE_SWIPE
	db 25, AURA_SPHERE
	db 28, IRON_TAIL
	db 32, WATERFALL
	db 36, SURF
	db 40, AURORA_BEAM
	db 44, HYDRO_PUMP
	db 0 ; no more level-up moves
