	db EVOLVE_ITEM, MOON_STONE, NIDOQUEEN
	db 1, GROWL
	db 1, SCRATCH
	db 4, POISON_STING
	db 8, DOUBLE_KICK
	db 10, FURY_SWIPES
	db 13, BITE
	db 16, SLUDGE
	db 19, MUD_SLAP
	db 22, SLUDGE_BOMB
	db 25, EARTH_POWER
	db 34, TOXIC
	db 37, EARTH_POWER
	db 40, SLUDGE_BOMB
	db 49, EARTH_POWER
	db 52, SLUDGE_BOMB
	db 0 ; no more level-up moves
