	db 0 ; no more evolutions
	db 1, METAL_CLAW
	db 1, QUICK_ATTACK
	db 4, BULLET_PUNCH
	db 7, TWINEEDLE
	db 10, METAL_CLAW
	db 13, SHARPEN
	db 16, FALSE_SWIPE
	db 19, BULLET_PUNCH
	db 22, FURY_CUTTER
	db 25, IRON_HEAD
	db 28, DOUBLE_TEAM
	db 31, FALSE_SWIPE
	db 34, SLASH
	db 37, IRON_HEAD
	db 40, PURSUIT
	db 43, X_SCISSOR
	db 46, TWINEEDLE
	db 49, IRON_HEAD
	db 52, SWORDS_DANCE
	db 55, FALSE_SWIPE
	db 0 ; no more level-up moves
