	db EVOLVE_LEVEL, 32, MEGANIUM
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, GROWL
	db 1, RAZOR_LEAF
	db 1, POISONPOWDER
	db 6, RAZOR_LEAF
	db 9, POISONPOWDER
	db 12, SYNTHESIS
	db 18, BODY_SLAM
	db 21, SYNTHESIS
	db 23, MAGICAL_LEAF
	db 26, NATURAL_GIFT
	db 29, POISON_POWDER
	db 32, SLEEP_POWDER
	db 36, PLAY_ROUGH
	db 40, BODY_SLAM
	db 46, SEED_BOMB
	db 50, AROMATHERAPY
	db 54, SOLARBEAM
	db 0 ; no more level-up moves