	db EVOLVE_LEVEL, 25, AMBIPOM
	db 0 ; no more evolutions
	db 1, SCRATCH
	db 1, TAIL_WHIP
	db 4, ASTONISH
	db 7, FURY_SWIPES
	db 10, VINE_WHIP
	db 13, FALSE_SWIPE
	db 16, SCREECH
	db 19, ASTONISH
	db 20, FALSE_SWIPE
	db 22, DOUBLE_HIT
	db 25, STRENGTH
	db 28, SEED_BOMB
	db 31, FALSE_SWIPE
	db 34, SHADOW_CLAW
	db 37, DOUBLE_HIT
	db 40, STRENGTH
	db 40, FALSE_SWIPE
	db 43, SEED_BOMB
	db 46, SCREECH
	db 49, SHADOW_CLAW
	db 52, STRENGTH
	db 0 ; no more level-up moves
