	db EVOLVE_ITEM, SHINY_STONE, DUNSPARCE
	db EVOLVE_LEVEL, 30, RHYDON
	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, TACKLE
	db 4, ROCK_THROW
	db 7, HORN_ATTACK
	db 10, BULLDOZE
	db 15, HORN_ATTACK
	db 20, SCARY_FACE
	db 25, STOMP
	db 30, ROCK_BLAST
	db 34, DRILL_RUN
	db 38, DOUBLE_EDGE
	db 41, FALSE_SWIPE
	db 43, SCARY_FACE
	db 46, STOMP
	db 49, ROCK_SLIDE
	db 52, BODY_SLAM
	db 56, MEGAHORN
	db 59, STONE_EDGE
	db 61, EARTHQUAKE
	db 64, TAKE_DOWN
	db 68, HORN_DRILL
	db 0 ; no more level-up moves
