	db EVOLVE_ITEM, SHINY_STONE, GOLETT
	db EVOLVE_LEVEL, 21, LAMPENT
	db 0 ; no more evolutions
	db 1, ASTONISH
	db 1, EMBER
	db 4, MINIMIZE
	db 7, WILL_O_WISP
	db 10, CONFUSE_RAY
	db 13, NIGHT_SHADE
	db 16, EMBER
	db 19, SHADOW_BALL
	db 22, FIRE_SPIN
	db 25, CONFUSE_RAY
	db 28, NIGHT_SHADE
	db 31, WILL_O_WISP
	db 34, SHADOW_BALL
	db 37, FLAMETHROWER
	db 40, CONFUSE_RAY
	db 43, NIGHT_SHADE
	db 46, WILL_O_WISP
	db 49, SHADOW_BALL
	db 52, FLAMETHROWER
	db 0 ; no more level-up moves
