	db 0 ; no more evolutions
	db 1, CONSTRICT
	db 1, WITHDRAW
	db 4, WRAP
	db 7, DEFENSE_CURL
	db 7, ROLLOUT
	db 10, STRUGGLE_BUG
	db 13, IRON_DEFENSE
	db 16, WRAP
	db 19, DOUBLE_TEAM
	db 22, ATTRACT
	db 25, STRUGGLE_BUG
	db 28, IRON_DEFENSE
	db 31, DOUBLE_TEAM
	db 34, ATTRACT
	db 37, STRUGGLE_BUG
	db 40, TOXIC
	db 43, RECOVER
	db 46, DEFENSE_CURL
	db 46, ROLLOUT
	db 49, STRUGGLE_BUG
	db 52, TOXIC
	db 0 ; no more level-up moves
