	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, CURSE
	db 4, METAL_CLAW
	db 7, ANCIENTPOWER
	db 10, STOMP
	db 13, AMNESIA
	db 16, IRON_HEAD
	db 19, SAFEGUARD
	db 22, FLASH_CANNON
	db 25, ZAP_CANNON
	db 28, DARK_PULSE
	db 31, STOMP
	db 34, CURSE
	db 37, IRON_HEAD
	db 40, HYPER_BEAM
	db 43, DARK_PULSE
	db 46, ZAP_CANNON
	db 49, CURSE
	db 52, IRON_HEAD
	db 55, STOMP
	db 58, ANCIENTPOWER
	db 61, ZAP_CANNON
	db 64, DARK_PULSE
	db 67, FLASH_CANNON
	db 80, EXPLOSION
	db 0 ; no more level-up moves
