	db 0 ; no more evolutions
	db 1, GROWTH
	db 1, ABSORB
	db 4, ACID
	db 7, SWEET_SCENT
	db 10, POISON_POWDER
	db 13, MEGA_DRAIN
	db 16, SLUDGE
	db 19, MOONLIGHT
	db 22, GIGA_DRAIN
	db 25, SLUDGE_BOMB
	db 29, DARK_PULSE
	db 31, TOXIC
	db 34, SLEEP_POWER
	db 37, MOONBLAST
	db 41, GRASSY_TERRAIN
	db 45, MOONLIGHT
	db 49, PETAL_DANCE
	db 52, DARK_PULSE
	db 55, SLUDGE_BOMB
	db 58, PETAL_BLIZZARD
	db 0 ; no more level-up moves
