	db EVOLVE_LEVEL, 24, HARIYAMA
	db 0 ; no more evolutions
	db 1, SAND_ATTACK
	db 1, TACKLE
	db 4, KARATE_CHOP
	db 7, MUD_SLAP
	db 10, DIG
	db 13, SEISMIC_TOSS
	db 16, BODY_SLAM
	db 19, KARATE_CHOP
	db 22, VITAL_THROW
	db 25, DIG
	db 28, BODY_SLAM
	db 31, MACH_PUNCH
	db 34, BULLET_PUNCH
	db 37, VITAL_THROW
	db 40, EARTHQUAKE
	db 43, MACH_PUNCH
	db 46, BULLET_PUNCH
	db 49, VITAL_THROW
	db 52, EARTHQUAKE
	db 0 ; no more level-up moves
