	db EVOLVE_LEVEL, 37, BANETTE
	db 0 ; no more evolutions
	db 1, SCRATCH
	db 1, ASTONISH
	db 4, DISABLE
	db 7, SCARY_FACE
	db 10, SHADOW_BALL
	db 13, FEINT_ATTACK
	db 16, HEADBUTT
	db 19, NIGHT_SHADE
	db 20, FALSE_SWIPE
	db 22, SHADOW_CLAW
	db 25, SCARY_FACE
	db 28, CURSE
	db 30, FALSE_SWIPE
	db 31, HEADBUTT
	db 34, SHADOW_CLAW
	db 37, SLASH
	db 40, NIGHT_SHADE
	db 40, FALSE_SWIPE
	db 43, CURSE
	db 46, SCARY_FACE
	db 49, SLASH
	db 52, SHADOW_CLAW
	db 0 ; no more level-up moves
