	db EVOLVE_LEVEL, 33, GOLURK
	db 0 ; no more evolutions
	db 1, ASTONISH
	db 1, MUD_SLAP
	db 4, DEFENSE_CURL
	db 7, POUND
	db 10, KARATE_CHOP
	db 13, SHADOW_CLAW
	db 16, BONE_CLUB
	db 19, NIGHT_SHADE
	db 22, MEGA_PUNCH
	db 25, DIZZY_PUNCH
	db 28, SHADOW_CLAW
	db 31, BONE_CLUB
	db 34, DRAIN_PUNCH
	db 37, EARTHQUAKE
	db 40, MEGA_PUNCH
	db 43, SHADOWCLAW
	db 46, EARTHQUAKE
	db 49, DRAIN_PUNCH
	db 52, DYNAMICPUNCH
	db 0 ; no more level-up moves
