	db 0 ; no more evolutions
	db 1, FLASH
	db 1, TACKLE
	db 4, TWINEEDLE
	db 7, MOONLIGHT
	db 10, DOUBLE_TEAM
	db 13, CONFUSE_RAY
	db 16, STRUGGLE_BUG
	db 19, TWINEEDLE
	db 22, FLASH
	db 25, QUICK_ATTACK
	db 28, MOONLIGHT
	db 31, SWORDS_DANCE
	db 34, PLAY_ROUGH
	db 37, ZEN_HEADBUTT
	db 40, QUICK_ATTACK
	db 43, MOONLIGHT
	db 46, SWORDS_DANCE
	db 49, TWINEEDLE
	db 52, PLAY_ROUGH
	db 0 ; no more level-up moves
