	db EVOLVE_HAPPINESS, TR_NITE, CHIMECHO
	db EVOLVE_LEVEL, 20, CHIMECHO
	db 0 ; no more evolutions
	db 1, ASTONISH
	db 1, CONFUSION
	db 4, GROWL
	db 7, WRAP
	db 10, SWIFT
	db 13, CONFUSION
	db 16, ASTONISH
	db 19, CHARM
	db 22, SWIFT
	db 25, PSYBEAM
	db 28, SHADOW_BALL
	db 31, CHARM
	db 34, HYPER_VOICE
	db 37, PSYCHIC
	db 40, SHADOW_BALL
	db 43, CHARM
	db 46, HYPER_VOICE
	db 49, PSYCHIC
	db 52, SHADOW_BALL
	db 0 ; no more level-up moves
