	db EVOLVE_ITEM, WATER_STONE, ARTICUNO
	db 0 ; no more evolutions
	db 1, PECK
	db 1, MUD_SLAP
	db 4, SAND_ATTACK
	db 7, FURY_ATTACK
	db 10, METAL_CLAW
	db 13, HARDEN
	db 16, FALSE_SWIPE
	db 19, WING_ATTACK
	db 22, METAL_CLAW
	db 25, SLASH
	db 28, FALSE_SWIPE
	db 31, MUD_SLAP
	db 34, STEEL_WING
	db 37, DRILL_PECK
	db 40, SLASH
	db 43, FALSE_SWIPE
	db 46, MUD_SLAP
	db 49, STEEL_WING
	db 52, DRILL_PECK
	db 0 ; no more level-up moves
