	db EVOLVE_LEVEL, 35, EXPLOUD
	db 0 ; no more evolutions
	db 1, THUNDERSHOCK
	db 1, POUND
	db 4, GROWL
	db 7, SUPERSONIC
	db 10, SMOKESCREEN
	db 13, STOMP
	db 16, SHOCK_WAVE
	db 19, GROWTH
	db 22, SCREECH
	db 25, THUNDERPUNCH
	db 28, SWIFT
	db 31, THUNDERBOLT
	db 34, BODY_SLAM
	db 37, HYPER_VOICE
	db 40, UPROAR
	db 43, THUNDERPUNCH
	db 46, THUNDERBOLT
	db 49, BODY_SLAM
	db 52, HYPER_VOICE
	db 0 ; no more level-up moves
