	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, HARDEN
	db 4, ROCK_THROW
	db 7, THUNDERWAVE
	db 10, THUNDERSHOCK
	db 13, ROLLOUT
	db 16, IRON_DEFENSE
	db 19, SPARK
	db 22, ROCK_SLIDE
	db 25, POWER_GEM
	db 28, SHOCK_WAVE
	db 31, EARTH_POWER
	db 34, ZAP_CANNON
	db 37, FLASH_CANNON
	db 40, POWER_GEM
	db 43, EARTH_POWER
	db 46, ZAP_CANNON
	db 49, FLASH_CANNON
	db 52, POWER_GEM
	db 0 ; no more level-up moves
