	db EVOLVE_ITEM, ICE_STONE, SUICUNE
	db 0 ; no more evolutions
	db 1, TAIL_WHIP
	db 1, WATER_GUN
	db 4, SAND_ATTACK
	db 7, QUICK_ATTACK
	db 10, SWIFT
	db 13, BITE
	db 16, CHARM
	db 19, BUBBLEBEAM
	db 22, WATER_GUN
	db 25, ACID_ARMOR
	db 28, MUDDY_WATER
	db 31, SURF
	db 34, BUBBLEBEAM
	db 37, AURORA_BEAM
	db 40, ACID_ARMOR
	db 43, ICE_BEAM
	db 46, MIST
	db 49, HYPER_VOICE
	db 52, HYDRO_PUMP
	db 56, BLIZZARD
	db 0 ; no more level-up moves
