	db EVOLVE_ITEM, WATER_STONE, SEEL
	db EVOLVE_ITEM, ICE_STONE, MUDKIP
	db 0 ; no more evolutions
	db 1, MUD_SLAP
	db 1, BUBBLE
	db 4, SLAM
	db 7, AMNESIA
	db 10, RECOVER
	db 13, ACID
	db 16, MUD_SLAP
	db 19, WATER_GUN
	db 22, RECOVER
	db 25, EARTH_POWER
	db 28, BUBBLEBEAM
	db 31, SLUDGE
	db 34, RECOVER
	db 37, EARTH_POWER
	db 40, BUBBLEBEAM
	db 41, SURF
	db 43, SLUDGE_BOMB
	db 46, RECOVER
	db 49, EARTH_POWER
	db 52, HYDRO_PUMP
	db 52, SURF
	db 0 ; no more level-up moves
