	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, CONFUSION
	db 4, METAL_CLAW
	db 7, CONFUSE_RAY
	db 10, IRON_DEFENSE
	db 13, SAFEGUARD
	db 16, METAL_CLAW
	db 19, HYPNOSIS
	db 22, CONFUSE_RAY
	db 25, HYPNOSIS
	db 28, SAFEGUARD
	db 31, PSYBEAM
	db 34, FLASH_CANNON
	db 37, PSYCHIC
	db 40, HYPNOSIS
	db 43, SAFEGUARD
	db 46, CONFUSE_RAY
	db 49, FLASH_CANNON
	db 52, PSYCHIC
	db 0 ; no more level-up moves
