	db EVOLVE_LEVEL, 30, MUK
	db 1, POISON_STING
	db 1, POUND
	db 4, HARDEN
	db 7, METAL_CLAW
	db 10, POISON_POWDER
	db 13, DISABLE
	db 16, METAL_CLAW
	db 19, POISON_JAB
	db 22, IRON_HEAD
	db 25, MINIMIZE
	db 28, ACID_ARMOR
	db 31, POISON_JAB
	db 34, METEOR_MASH
	db 37, TOXIC
	db 40, MINIMIZE
	db 43, ACID_ARMOR
	db 46, METEOR_MASH
	db 49, POISON_JAB
	db 52, TOXIC
	db 0 ; no more level-up moves
