	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, STRING_SHOT
	db 1, STRUGGLE_BUG
	db 1, HARDEN
	db 10, SUPERSONIC
	db 10, CONFUSION
	db 10, GUST
	db 12, STUN_SPORE
	db 14, BUG_BUZZ
	db 16, PSYBEAM
	db 18, AIR_CUTTER
	db 20, SLEEP_POWDER
	db 22, SAFEGUARD
	db 24, AIR_SLASH
	db 26, BUG_BUZZ
	db 28, PSYBEAM
	db 30, AIR_SLASH
	db 32, BUG_BUZZ
	db 34, SLEEP_POWDER
	db 36, PSYBEAM
	db 38, AIR_SLASH
	db 40, BUG_BUZZ
	db 42, QUICER_DANCE
	db 0 ; no more level-up moves
