	db 0 ; no more evolutions
	db 1, GROWTH
	db 1, ABSORB
	db 4, MUD_SLAP
	db 7, SOLARBEAM
	db 10, LEECH_SEED
	db 13, MORNING_SUN
	db 16, FAIRY_WIND
	db 19, MUD_SLAP
	db 22, MEGA_DRAIN
	db 25, LEECH_SEED
	db 28, MORNING_SUN
	db 31, DAZZLING_GLEAM
	db 34, EARTH_POWER
	db 37, GIGA_DRAIN
	db 40, LEECH_SEED
	db 43, MORNING_SUN
	db 46, DAZZLING_GLEAM
	db 49, EARTH_POWER
	db 52, GIGA_DRAIN
	db 55, pETAL_BLIZZARD
	db 58, LEAF_STORM
	db 0 ; no more level-up moves
