	db EVOLVE_ITEM, SHINY_STONE, TANGELA
	db EVOLVE_LEVEL, 21, GLOOM
	db EVOLVE_ITEM, lEAF_STONE, BELLSPROUT
	db EVOLVE_ITEM, SUN_STONE, SUNKERN
	db 1, GROWTH
	db 1, ABSORB
	db 4, ACID
	db 7, SWEET_SCENT
	db 10, POISON_POWDER
	db 13, MEGA_DRAIN
	db 16, SLUDGE
	db 19, MOONLIGHT
	db 22, GIGA_DRAIN
	db 25, SLUDGE_BOMB
	db 28, STUN_SPORE
	db 31, TOXIC
	db 34, GIGA_DRAIN
	db 37, SLUDGE_BOMB
	db 40, STUN_SPORE
	db 43, TOXIC
	db 46, GIGA_DRAIN
	db 49, SLUDGE_BOMB
	db 52, STUN_SPORE
	db 0 ; no more level-up moves
