	db EVOLVE_LEVEL, 45, METAGROSS
	db 0 ; no more evolutions
	db 1, TACKLE
	db 1, BULLET_PUNCH
	db 20, METAL_CLAW
	db 20, CONFUSION
	db 22, FLASH_CANNON
	db 25, BULLET_PUNCH
	db 28, IRON_HEAD
	db 31, PSYBEAM
	db 34, MAGNET_RISE
	db 37, IRON_DEFENSE
	db 40, IRON_HEAD
	db 43, FLASH_CANNON
	db 46, PSYCHIC
	db 49, METEOR_MASH
	db 52, ZEN_HEADBUTT
	db 0 ; no more level-up moves
