	db EVOLVE_LEVEL, 32, CLOYSTER
	db 1, CLAMP
	db 1, WITHDRAW
	db 4, WATER_GUN
	db 7, SUPERSONIC
	db 10, CLAMP
	db 13, WITHDRAW
	db 16, LICK
	db 19, WHIRLPOOL
	db 22, AQUA_JET
	db 25, LICK
	db 28, IRON_DEFENSE
	db 31, HORN_ATTACK
	db 34, CLAMP
	db 37, ICE_PUNCH
	db 40, AQUA_JET
	db 43, LICK
	db 46, SPIKE_CANNON
	db 49, ICE_PUNCH
	db 52, AQUA_JET
	db 0 ; no more level-up moves
